version: '3'
services:
  master:
    build: .
    hostname: master
    container_name: hpcc_master
    volumes:
      - ./shared:/shared
    ports:
      - "2222:22"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.2

  node01:
    build: .
    hostname: node01
    container_name: hpcc_node01
    volumes:
      - ./shared:/shared
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.3

  node02:
    build: .
    hostname: node02
    container_name: hpcc_node02
    volumes:
      - ./shared:/shared
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.4

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24 


        